### ISSUE TITLE
Šumniki ne spadajo v imena razredov, spremenljivk, metod, ...

### ISSUE THREAD

**Issue by andrejbauer** [matejxx1/SnowflipperPenguin#1]
Prosim, da se jih odstrani.

**Comment by matejxx1** [comment]
Sva popravila.

**Comment by andrejbauer** [comment]
**NAROBE ZAPRT ISSUE**, preberita na forumu v spletnih učilnici, kako se to naredi prav.

**Comment by andrejbauer** [comment]
Najlepša hvala.
